# Generated by Django 3.2.17 on 2023-02-14 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230214_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sold_item',
            old_name='name',
            new_name='product',
        ),
    ]
